#!/usr/bin/env bash
# Pulse production deploy — Oracle Always Free / any Ubuntu 22.04+ VM.
#
#   git clone https://github.com/Makrand10/pulse.git
#   cd pulse
#   sudo bash scripts/deploy/deploy.sh
#
# Idempotent: safe to re-run to pull + redeploy updates.
set -euo pipefail

STEP() { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }

# ---- 1. Docker + Compose plugin ----
if ! command -v docker >/dev/null 2>&1; then
  STEP 'Installing Docker Engine'
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
fi
if ! docker compose version >/dev/null 2>&1; then
  STEP 'Installing Docker Compose plugin'
  apt-get update
  apt-get install -y docker-compose-plugin
fi
usermod -aG docker "$SUDO_USER" 2>/dev/null || true

# ---- 2. .env (secrets, generated once) ----
if [ ! -f .env ]; then
  STEP 'Generating .env with fresh secrets'
  PUBLIC_IP="$(curl -fsSL https://checkip.amazonaws.com || echo localhost)"
  cat > .env <<EOF
# Generated by scripts/deploy/deploy.sh — do not commit
JWT_SECRET=$(openssl rand -base64 48)
ENCRYPTION_KEY=$(openssl rand -base64 32)
APP_BASE_URL=http://${PUBLIC_IP}
AI_PROVIDER=groq
AI_ENABLED=true
AI_DAILY_CALL_CAP=10
PULSE_FRONTEND_PORT=80
BACKEND_HOST_IP=127.0.0.1
EOF
else
  STEP 'Using existing .env'
fi

# ---- 3. Build + start the full stack ----
STEP 'Building and starting containers (first build takes a few minutes)'
docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

STEP 'Waiting for the backend healthcheck'
for i in $(seq 1 30); do
  if curl -fsS http://127.0.0.1:4000/readyz >/dev/null 2>&1; then
    echo 'Backend: ready'
    break
  fi
  [ "$i" -eq 30 ] && echo 'WARN: /readyz not ready yet — check `docker compose -f docker-compose.yml -f docker-compose.prod.yml logs backend`'
  sleep 5
done

# ---- 4. Summary ----
PUBLIC_URL="$(grep '^APP_BASE_URL=' .env | cut -d= -f2-)"
echo
echo '=================================================='
echo "  Pulse is live at:  $PUBLIC_URL"
echo '  API (localhost only): http://127.0.0.1:4000/healthz'
echo '  Stop:  docker compose -f docker-compose.yml -f docker-compose.prod.yml down'
echo '  Logs:  docker compose -f docker-compose.yml -f docker-compose.prod.yml logs -f --tail=100 backend'
echo '=================================================='